/**
 * BakedModelLoader - Runtime loader for pre-baked model geometry and metadata
 * 
 * This module loads the binary data generated by scripts/bake-model-geometry.js
 * and provides O(1) lookups for block flags, variant geometry, and metadata.
 * 
 * Binary Format (from bake-model-geometry.js):
 * [header]
 *   u32: magic (0x424B4D44 = "BKMD")
 *   u32: version
 *   u32: block count
 * 
 * [block index] (for each block)
 *   u16: block name length
 *   bytes: block name (UTF-8)
 *   u32: offset to block data from start of data section
 * 
 * [block data] (for each block)
 *   u8: variant count
 *   u8: flags bitfield:
 *       0x01 = hasRandomRotation
 *       0x02 = hasPositionOffset
 *       0x04 = isTransparent
 *       0x08 = noShade
 *       0x10 = hasInnerCube
 *       0x20 = hasAxisRotation
 *   [variant] (for each variant)
 *     ...
 */

// Flag bit constants (must match bake-model-geometry.js)
export const FLAG_RANDOM_ROTATION = 0x01;
export const FLAG_POSITION_OFFSET = 0x02;
export const FLAG_TRANSPARENT = 0x04;
export const FLAG_NO_SHADE = 0x08;
export const FLAG_INNER_CUBE = 0x10;
export const FLAG_AXIS_ROTATION = 0x20;

let instance = null;

export class BakedModelLoader {
  constructor() {
    // Baked data
    this.vanillaData = null;      // DataView for baked-models.bin
    this.vanillaTextureMap = null; // Map of texture name -> index
    
    // Lookup tables (built after loading)
    this.blockNameToIndex = new Map();  // blockName -> index in binary
    this.blockOffsets = [];              // index -> byte offset to block data
    this.blockFlags = null;              // Uint8Array[blockCount] for O(1) flag lookup
    this.blockCount = 0;
    
    // Data section offset
    this._dataStart = 0;
  }
  
  /**
   * Load vanilla baked data from server
   * @returns {Promise<boolean>} True if successful
   */
  async load() {
    if (this.isLoaded()) {
      console.log('[BakedModelLoader] Already loaded');
      return true;
    }
    
    try {
      const baseUrl = import.meta.env?.BASE_URL || '/';
      
      // Load binary geometry data
      const [binResponse, texResponse] = await Promise.all([
        fetch(`${baseUrl}assets/baked-models.bin`),
        fetch(`${baseUrl}assets/baked-models-textures.json`),
      ]);
      
      if (!binResponse.ok || !texResponse.ok) {
        throw new Error(`Failed to fetch baked data: ${binResponse.status}, ${texResponse.status}`);
      }
      
      const [buffer, textureMap] = await Promise.all([
        binResponse.arrayBuffer(),
        texResponse.json(),
      ]);
      
      this.vanillaData = new DataView(buffer);
      this.vanillaTextureMap = new Map(Object.entries(textureMap));
      
      // Build lookup tables
      this._buildLookups();
      
      console.log(`[BakedModelLoader] Loaded ${this.blockCount} blocks, ${(buffer.byteLength / 1024).toFixed(1)} KB`);
      
      return true;
    } catch (error) {
      console.error('[BakedModelLoader] Failed to load:', error);
      return false;
    }
  }
  
  /**
   * Build lookup tables from the binary data
   */
  _buildLookups() {
    const data = this.vanillaData;
    let offset = 0;
    
    // Read header
    const magic = data.getUint32(offset, true); offset += 4;
    if (magic !== 0x424B4D44) {
      throw new Error(`Invalid magic: ${magic.toString(16)}`);
    }
    
    const version = data.getUint32(offset, true); offset += 4;
    this.blockCount = data.getUint32(offset, true); offset += 4;
    
    // Read block index
    const indexStart = offset;
    let indexSize = 0;
    
    for (let i = 0; i < this.blockCount; i++) {
      const nameLen = data.getUint16(offset, true); offset += 2;
      
      // Read block name
      const nameBytes = new Uint8Array(data.buffer, offset, nameLen);
      const blockName = new TextDecoder().decode(nameBytes);
      offset += nameLen;
      
      // Read data offset
      const dataOffset = data.getUint32(offset, true); offset += 4;
      
      // Store in lookup
      this.blockNameToIndex.set(blockName, i);
      this.blockOffsets.push(dataOffset);
      indexSize += 2 + nameLen + 4;
    }
    
    // Data section starts after index
    this._dataStart = indexStart + indexSize;
    
    // Build flags array for O(1) lookup
    this.blockFlags = new Uint8Array(this.blockCount);
    
    for (let i = 0; i < this.blockCount; i++) {
      const blockDataOffset = this._dataStart + this.blockOffsets[i];
      // Skip variant count (1 byte), read flags (1 byte)
      this.blockFlags[i] = data.getUint8(blockDataOffset + 1);
    }
  }
  
  /**
   * Check if loader has data available
   * @returns {boolean}
   */
  isLoaded() {
    return this.vanillaData !== null && this.blockFlags !== null;
  }
  
  /**
   * Get the block index by name
   * @param {string} blockName - Block name (without minecraft: prefix)
   * @returns {number} Block index or -1 if not found
   */
  getBlockIndex(blockName) {
    const normalized = blockName.replace('minecraft:', '');
    return this.blockNameToIndex.get(normalized) ?? -1;
  }
  
  /**
   * Get flags for a block (O(1) lookup)
   * @param {number} blockIndex - Block index from getBlockIndex()
   * @returns {number} Flags bitfield, or 0 if invalid index
   */
  getFlags(blockIndex) {
    if (blockIndex < 0 || blockIndex >= this.blockCount) {
      return 0;
    }
    return this.blockFlags[blockIndex];
  }
  
  /**
   * Get flags for a block by name
   * @param {string} blockName - Block name
   * @returns {number} Flags bitfield
   */
  getFlagsByName(blockName) {
    const index = this.getBlockIndex(blockName);
    return this.getFlags(index);
  }
  
  /**
   * Check if block has random rotation
   * @param {string} blockName - Block name
   * @returns {boolean}
   */
  hasRandomRotation(blockName) {
    return (this.getFlagsByName(blockName) & FLAG_RANDOM_ROTATION) !== 0;
  }
  
  /**
   * Check if block needs position offset
   * @param {string} blockName - Block name
   * @returns {boolean}
   */
  hasPositionOffset(blockName) {
    return (this.getFlagsByName(blockName) & FLAG_POSITION_OFFSET) !== 0;
  }
  
  /**
   * Check if block is transparent
   * @param {string} blockName - Block name
   * @returns {boolean}
   */
  isTransparent(blockName) {
    return (this.getFlagsByName(blockName) & FLAG_TRANSPARENT) !== 0;
  }
  
  /**
   * Check if block has no shade
   * @param {string} blockName - Block name
   * @returns {boolean}
   */
  hasNoShade(blockName) {
    return (this.getFlagsByName(blockName) & FLAG_NO_SHADE) !== 0;
  }
  
  /**
   * Check if block has inner cube
   * @param {string} blockName - Block name
   * @returns {boolean}
   */
  hasInnerCube(blockName) {
    return (this.getFlagsByName(blockName) & FLAG_INNER_CUBE) !== 0;
  }
  
  /**
   * Check if block has axis rotation (logs, pillars)
   * @param {string} blockName - Block name
   * @returns {boolean}
   */
  hasAxisRotation(blockName) {
    return (this.getFlagsByName(blockName) & FLAG_AXIS_ROTATION) !== 0;
  }
  
  /**
   * Get variant count for a block
   * @param {string} blockName - Block name
   * @returns {number} Number of variants
   */
  getVariantCount(blockName) {
    const index = this.getBlockIndex(blockName);
    if (index < 0) return 0;
    
    const blockDataOffset = this._dataStart + this.blockOffsets[index];
    return this.vanillaData.getUint8(blockDataOffset);
  }
  
  /**
   * Get texture index for a texture path
   * @param {string} texturePath - Texture path (e.g., "block/stone")
   * @returns {number} Texture index, or 0 if not found
   */
  getTextureIndex(texturePath) {
    const normalized = texturePath.replace('minecraft:', '').replace('block/', '');
    return this.vanillaTextureMap?.get(normalized) ?? 0;
  }
  
  /**
   * Get all block names
   * @returns {string[]} Array of block names
   */
  getAllBlockNames() {
    return [...this.blockNameToIndex.keys()];
  }
  
  /**
   * Get the raw binary data (for WASM initialization)
   * @returns {Uint8Array} Raw binary data
   */
  getRawData() {
    return new Uint8Array(this.vanillaData.buffer);
  }
}

/**
 * Get the singleton instance of BakedModelLoader
 * @returns {BakedModelLoader}
 */
export function getBakedModelLoader() {
  if (!instance) {
    instance = new BakedModelLoader();
  }
  return instance;
}

/**
 * Load the baked model data (convenience function)
 * @returns {Promise<BakedModelLoader>}
 */
export async function loadBakedModels() {
  const loader = getBakedModelLoader();
  if (!loader.isLoaded()) {
    await loader.load();
  }
  return loader;
}

export default BakedModelLoader;
